### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'count')

### ISSUE THREAD

**Issue by alex-marinov** [pmndrs/react-three-csg#29]
I'm getting this error when trying to use the cgs library, here is the [codesandbox link](https://codesandbox.io/p/devbox/weathered-mountain-ftsrx9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqjv9nbu00073b6hyqpqfgzz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqjv9nbu00023b6hegl3wvv6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqjv9nbu00043b6hecs19aly%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqjv9nbu00063b6hc1tx9ult%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqjv9nbu00023b6hegl3wvv6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqjv9nbu00013b6hz8bca170%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqjv9nbu00023b6hegl3wvv6%2522%252C%2522activeTabId%2522%253A%2522clqjv9nbu00013b6hz8bca170%2522%257D%252C%2522clqjv9nbu00063b6hc1tx9ult%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqjv9nbu00053b6hmeyt0zu3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqjv9nbu00063b6hc1tx9ult%2522%252C%2522activeTabId%2522%253A%2522clqjv9nbu00053b6hmeyt0zu3%2522%257D%252C%2522clqjv9nbu00043b6hecs19aly%2522%253A%257B%2522id%2522%253A%2522clqjv9nbu00043b6hecs19aly%2522%252C%2522activeTabId%2522%253A%2522clqjvh76j00sg3b6hakzpj7v6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqjvav3h00233b6h3yw3h6la%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqjvav5m01aqefgehjssfxdm%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqjvh76j00sg3b6hakzpj7v6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

TypeError: Cannot read properties of undefined (reading 'count')
    at Module.ensureIndex (/_next/static/chunks/node_modules_three-bvh-csg_src_7fbc42._.js:41:53)
    at Brush.prepareGeometry (/_next/static/chunks/node_modules_three-bvh-csg_src_7fbc42._.js:1128:186)
    at Evaluator.evaluate (/_next/static/chunks/node_modules_three-bvh-csg_src_7fbc42._.js:2179:11)
    at /_next/static/chunks/node_modules_022a0c._.js:2041:43
    at /_next/static/chunks/node_modules_022a0c._.js:2070:188
    at commitHookEffectListMount (node_modules_react-reconciler_7f1098._.js:11966:42)
    at commitLayoutEffectOnFiber (node_modules_react-reconciler_7f1098._.js:12057:41)
    at commitLayoutMountEffects_complete (node_modules_react-reconciler_7f1098._.js:13280:25)
    at commitLayoutEffects_begin (node_modules_react-reconciler_7f1098._.js:13269:21)
    at commitLayoutEffects_begin (node_modules_react-reconciler_7f1098._.js:13255:29)
    at commitLayoutEffects (node_modules_react-reconciler_7f1098._.js:13219:13)
    at commitRootImpl (node_modules_react-reconciler_7f1098._.js:15434:17)
    at commitRoot (node_modules_react-reconciler_7f1098._.js:15330:17)
    at finishConcurrentRender (node_modules_react-reconciler_7f1098._.js:14728:25)
    at performConcurrentWorkOnRoot (node_modules_react-reconciler_7f1098._.js:14592:21)
    at workLoop (/_next/static/chunks/node_modules_022a0c._.js:280:48)
    at flushWork (/_next/static/chunks/node_modules_022a0c._.js:259:28)
    at MessagePort.performWorkUntilDeadline (/_next/static/chunks/node_modules_022a0c._.js:487:35)

Code:    
```typescript
"use client";

import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { Base, Geometry, Intersection } from "@react-three/csg";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Canvas>
        <ambientLight />
        <OrbitControls />
        <pointLight position={[10, 10, 10]} />
        <mesh>
          <meshNormalMaterial />
          <Geometry>
            <Base>
              <mesh position={[0, -1, 0]} rotation={[0, 45, 0]}>
                <boxGeometry args={[1, 1, 3]}></boxGeometry>
                <meshNormalMaterial />
              </mesh>
            </Base>
            <Intersection>
              <mesh position={[0, -1, 0]} rotation={[90, 0, 0]}>
                <cylinderGeometry args={[0.5, 0.5, 3, 32]}></cylinderGeometry>
                <meshNormalMaterial />
              </mesh>
            </Intersection>
          </Geometry>
        </mesh>
      </Canvas>
    </main>
  );
}
```

**Comment by alex-marinov** [comment]
🤦🏻‍♂️ just realised that I was passing a mesh, not a geometry! would be good to have a useful error message saying 'No valid geometry.' or something similar.
